/* 교과서 실험 — 교과서 탐구를 시뮬레이션으로 해 보고 하나만 바꿔 내 탐구로. 엔진: ../assets/inquiry.js
   교과서 쪽 번호는 비상교육 교과서. 내용은 교과서 문장을 옮기지 않고 짧게 줄여 새로 썼다. */
window.sthInquiry({ mount: "inq", key: "inq", result: "rInq", items: [
  { id: "e1", sec: "01", book: "지구과학", page: 60, title: "연안 용승과 식물성 플랑크톤 분포 해석", purpose: "아프리카 북서부 연안의 수온과 플랑크톤 분포로 연안 용승을 설명한다.",
    steps: ["연안에서 수온이 낮은 곳을 찾는다", "바람 방향과 에크만 수송으로 그 까닭을 설명한다", "플랑크톤이 많은 까닭을 영양 염류와 관련지어 설명한다"],
    iv: "연안으로부터의 거리", dv: "표층 수온(°C)·플랑크톤 농도(mg/m³)", cv: ["바람 방향과 세기", "위도"], safety: "",
    extend: ["바람 세기만 바꾸면 연안의 수온은 얼마나 낮아질까", "바람 방향만 남풍으로 바꾸면 용승이 일어날까", "위도만 바꾸면(전향력 크기) 같은 바람에서 용승 세기는?"],
    sim: { kind: "model", name: "가상 연안 용승", noise: 0.03,
      note: "북반구, 바다의 동쪽 해안(아프리카 북서부처럼 해안이 동쪽)을 가정합니다. 바람 응력 τ = 1.2 × 0.0013 × U², 에크만 수송 M = τ/(ρf), f = 2Ω sin(위도). 해안과 나란한 북풍이면 표층수가 바다 쪽으로 밀려 찬물이 올라오고, 연안 수온 하강 = 8 °C × (1 − e^(−M/2)), 바다 쪽으로 50 km마다 e배씩 줄어듭니다(먼바다 22 °C). 플랑크톤은 올라온 찬물(영양 염류)이 많을수록 늘도록 0.1 + 0.8 × (수온 하강) mg/m³로 둔 단순 모형입니다.",
      inputs: [{ k: "x", label: "연안으로부터의 거리", unit: "km", min: 0, max: 300, step: 10, value: 0 }, { k: "U", label: "바람 세기", unit: "m/s", min: 0, max: 15, step: 1, value: 8 }, { k: "lat", label: "위도", unit: "°N", min: 10, max: 40, step: 5, value: 20 }],
      choices: [{ k: "dir", label: "바람 방향(해안과 나란히)", opts: [["북풍(남쪽으로 붊)", 1], ["남풍(북쪽으로 붊)", -1]], value: 1 }],
      outputs: [{ k: "sst", label: "표층 수온", unit: "°C", dp: 1, expr: "(function(){var f=2*7.292e-5*Math.sin(lat*Math.PI/180),M=1.2*0.0013*U*U/(1025*f),g=1-Math.exp(-M/2),d=dir==1?-8*g:1*g;return 22+d*Math.exp(-x/50);})()" },
        { k: "chl", label: "식물성 플랑크톤 농도", unit: "mg/m³", dp: 2, expr: "(function(){var f=2*7.292e-5*Math.sin(lat*Math.PI/180),M=1.2*0.0013*U*U/(1025*f),g=1-Math.exp(-M/2),d=dir==1?-8*g:1*g,s=22+d*Math.exp(-x/50);return 0.1+0.8*Math.max(0,22-s);})()" }] } },
  { id: "e2", sec: "01", book: "지구과학", page: 62, title: "엘니뇨·라니냐 시기의 표층 수온과 기압 분포", purpose: "표층 수온 편차 분포로 엘니뇨·라니냐 때 동·서 태평양의 기압 변화를 추론한다.",
    steps: ["엘니뇨 시기의 표층 수온 편차를 읽는다", "라니냐 시기의 수온 편차와 비교한다", "동태평양과 서태평양의 기압이 어떻게 바뀌었을지 추론한다"],
    iv: "시기(엘니뇨/라니냐)", dv: "표층 수온 편차(°C)와 해면 기압(hPa)", cv: ["같은 계절(12월)", "같은 지점(적도 태평양)"], safety: "",
    extend: ["같은 엘니뇨 날짜에서 적도 경도만 바꿔 서쪽·동쪽 수온 편차 비교", "같은 지점에서 날짜만 엘니뇨 ↔ 라니냐로 바꿔 해면 기압 비교"],
    sim: { kind: "iframe", name: "earth :: 전 지구 바람·해양 지도(nullschool)", url: "https://earth.nullschool.net/", h: 560,
      ivControl: "Mode=Ocean, Overlay=SSTA(수온 편차)를 고르고 날짜를 2015-12-15(엘니뇨)와 2017-12-15(라니냐)로 바꾸기(2020년 뒤 날짜는 SSTA가 안 뜸). 기압은 Mode=Air, Overlay=MSLP", dvReading: "적도 태평양 서쪽·동쪽을 클릭해 나오는 수온 편차(°C)와 해면 기압(hPa)",
      x: { label: "적도에서 클릭한 경도(동경으로 셈, 서경 90° = 270)", unit: "°E" }, y: { label: "수온 편차", unit: "°C" } } },
  { id: "e3", sec: "03", book: "지구과학", page: 72, title: "지구 기온 변화와 온실 기체 농도의 관계", purpose: "기온 편차와 온실 기체 농도 그래프를 비교해 둘의 관계를 찾는다.",
    steps: ["기온 편차와 온실 기체 농도 그래프의 변화 경향을 비교한다", "두 변화의 관계를 설명한다", "농도가 늘어난 원인을 조사한다"],
    iv: "온실 기체 농도(ppm·ppb)", dv: "지구 표면 온도(°C)", cv: ["햇빛 조건", "구름 설정"], safety: "",
    extend: ["같은 농도에서 구름만 켜고 끄면 표면 온도는 어떻게 달라질까", "농도를 빙하시대 → 2020으로 한 단계씩 올리며 온도 오름 폭이 같은지 확인"],
    sim: { kind: "iframe", name: "PhET · 온실 효과", url: "https://phet.colorado.edu/sims/html/greenhouse-effect/latest/greenhouse-effect_ko.html", h: 600,
      ivControl: "‘온실가스 농도’ 슬라이더, 또는 시대 단추(빙하시대·1750·1950·2020)", dvReading: "표면 온도계 값(°C)과 화면에 표시되는 CO₂ 농도(ppm)",
      x: { label: "CO₂ 농도", unit: "ppm" }, y: { label: "표면 온도", unit: "°C" } } },
  { id: "e4", sec: "03", book: "지구과학", page: 74, title: "기후 변화 해결 방법 조사(미래 기후 전망 시뮬레이션)", purpose: "기후 변화를 줄이는 방법의 원리를 조사하고 방법에 따라 미래 기온이 어떻게 달라지는지 본다.",
    steps: ["제시된 해결 방법 가운데 하나를 고른다", "그 방법이 기후 변화를 줄이는 원리를 조사한다", "다른 해결 방법을 더 찾아 발표한다"],
    iv: "해결 방법(정책)의 세기", dv: "2100년 기온 상승(°C)", cv: ["다른 정책 슬라이더는 처음 값 그대로"], safety: "",
    extend: ["탄소 가격 슬라이더만 바꾸며 2100년 기온 상승 비교", "재생 에너지 지원만 바꿔 탄소 가격과 효과 크기 비교"],
    sim: { kind: "iframe", name: "En-ROADS 기후 해법 시뮬레이터", url: "https://en-roads.climateinteractive.org/scenario.html?lang=ko", h: 640,
      ivControl: "고른 해결 방법의 정책 슬라이더(예: 탄소 가격) 하나만 움직이기", dvReading: "화면 오른쪽 위의 2100년 기온 상승(°C)",
      x: { label: "정책 슬라이더 값(예: 탄소 가격)", unit: "$/t CO₂" }, y: { label: "2100년 기온 상승", unit: "°C" } } }
] });
